export const INC_CART_COUNT = "INC_CART_COUNT";
export const DEC_CART_COUNT = "DEC_CART_COUNT";
export const INS_FOOD = "INS_FOOD";
export const INS_BEVERAGE = "INS_BEVERAGE";
export const REM_FOOD = "REM_FOOD";
export const REM_BEVERAGE = "REM_BEVERAGE";
export const EMPTY_STATE = "EMPTY_STATE";

export const LOAD_INITIAL_STATE = "LOAD_INITIAL_STATE"
export const LOAD_INITIAL_STATE_SUCCESS = "LOAD_INITIAL_STATE_SUCCESS"
export const LOAD_INITIAL_STATE_ERROR = "LOAD_INITIAL_STATE_ERROR"