
export const SEND_ORDER = "SEND_ORDER";
export const SEND_ORDER_SUCCESS = "SEND_ORDER_SUCCESS";
export const SEND_ORDER_ERROR = "SEND_ORDER_ERROR";

export const SET_CHECKOUT_LOADING = "SET_CHECKOUT_LOADING";

export const SET_COMPLETED_STATUS = "SET_COMPLETED_STATUS";

export const RESET_CHECKOUT_STATE = "RESET_CHECKOUT_STATE"